// Copyright 2026 xgfone
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package stringx

import (
	"fmt"
	"sync/atomic"
)

// Generator generates strings of a requested byte length. MinLen must be
// non-negative. A non-positive length means MinLen(); a positive length below
// MinLen() causes a panic. Implementations must document their concurrency safety.
type Generator interface {
	// MinLen returns the minimum generated byte length, including any affixes.
	MinLen() int

	// Generate returns a string of the requested byte length.
	Generate(length int) string

	// Append appends exactly length bytes to dst, preserving its existing contents.
	// The length excludes the existing contents of dst. The caller owns the
	// returned buffer and must synchronize any concurrent access to it.
	Append(dst []byte, length int) []byte
}

var defaultGenerator atomic.Value

// Keep the stored type fixed when a setter receives a different implementation.
type generatorValue struct{ generator Generator }

func init() { SetDefaultGenerator(DateTimeMilliRandGenerator()) }

// DefaultGenerator returns the current default generator, initially
// DateTimeMilliRandGenerator(). It is safe to call concurrently with
// SetDefaultGenerator. Previously returned generators are unaffected by replacement.
func DefaultGenerator() Generator {
	return defaultGenerator.Load().(generatorValue).generator
}

// SetDefaultGenerator replaces the default generator. It panics if g is nil,
// including a typed nil, or has a negative MinLen. It is safe to call concurrently,
// but does not make the supplied generator itself safe for concurrent use.
func SetDefaultGenerator(g Generator) {
	checkGenerator(g)
	checkGeneratorLength(0, g.MinLen())
	defaultGenerator.Store(generatorValue{generator: g})
}

// FuncGenerator adapts an append function to Generator, which is safe for
// concurrent use if its callback is safe and callers do not share append buffers.
//
// Its zero value cannot generate strings; use NewGenerator to initialize it.
type FuncGenerator struct {
	minlen     int
	appendFunc func([]byte, int) []byte
}

// NewGenerator returns a generator with a non-negative minimum byte length.
// The callback receives a validated length and must append exactly that many
// bytes while preserving the existing buffer contents. An incorrect output
// length causes a panic. It panics if minlen is negative or appendFunc is nil.
func NewGenerator(minlen int, appendFunc func(dst []byte, length int) []byte) FuncGenerator {
	if minlen < 0 {
		panic("stringx.NewGenerator: minlen must not be negative")
	}
	if appendFunc == nil {
		panic("stringx.NewGenerator: appendFunc must not be nil")
	}
	return FuncGenerator{minlen: minlen, appendFunc: appendFunc}
}

// MinLen returns the minimum generated byte length.
func (g FuncGenerator) MinLen() int { return g.minlen }

// Generate returns a string of the requested byte length, independent of the
// buffer returned by the callback. See Generator for length handling.
func (g FuncGenerator) Generate(length int) string { return generateString(g, length) }

// Append appends to dst. See Generator for length handling.
func (g FuncGenerator) Append(dst []byte, length int) []byte {
	if g.appendFunc == nil {
		panic("stringx.FuncGenerator.Append: uninitialized generator")
	}
	length = checkGeneratorLength(length, g.minlen)
	oldlen := len(dst)
	dst = g.appendFunc(dst, length)
	checkGeneratedLength(len(dst)-oldlen, length)
	return dst
}

func generateString(g Generator, length int) string {
	length = checkGeneratorLength(length, g.MinLen())
	// Custom generators may retain the buffer, so the string needs its own copy.
	return string(g.Append(make([]byte, 0, length), length))
}

func checkGeneratorLength(length, minlen int) int {
	if minlen < 0 {
		panic("stringx.Generator: MinLen must not be negative")
	}
	if length <= 0 {
		return minlen
	}
	if length < minlen {
		panic(fmt.Sprintf("stringx.Generator: length must not be less than %d", minlen))
	}
	return length
}

func checkGeneratedLength(actual, expected int) {
	if actual != expected {
		panic(fmt.Sprintf("stringx.Generator: appended %d bytes, want %d", actual, expected))
	}
}

func checkGenerator(g Generator) {
	checkNonNil(g, "stringx.Generator: generator must not be nil")
}

var _ Generator = FuncGenerator{}
