// Copyright 2026 xgfone
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package stringx

// AffixGenerator wraps a generator with a prefix and suffix. Configuration
// methods return copies; they do not modify the receiver. Concurrent use requires
// a concurrency-safe underlying generator and separate append buffers.
// Its zero value needs [AffixGenerator.WithGenerator] before use, or use [NewAffixGenerator].
type AffixGenerator struct {
	prefix string
	suffix string

	generator Generator
}

// NewAffixGenerator returns a generator with initially empty affixes.
// It panics if generator is nil, including a typed nil.
func NewAffixGenerator(generator Generator) AffixGenerator {
	checkGenerator(generator)
	return AffixGenerator{generator: generator}
}

// Prefix returns the prefix.
func (g AffixGenerator) Prefix() string { return g.prefix }

// Suffix returns the suffix.
func (g AffixGenerator) Suffix() string { return g.suffix }

// Generator returns the underlying generator.
func (g AffixGenerator) Generator() Generator { return g.generator }

// WithPrefix returns a copy with the given prefix.
func (g AffixGenerator) WithPrefix(prefix string) AffixGenerator {
	g.prefix = prefix
	return g
}

// WithSuffix returns a copy with the given suffix.
func (g AffixGenerator) WithSuffix(suffix string) AffixGenerator {
	g.suffix = suffix
	return g
}

// WithGenerator returns a copy with the given generator.
// It panics if generator is nil, including a typed nil.
func (g AffixGenerator) WithGenerator(generator Generator) AffixGenerator {
	checkGenerator(generator)
	g.generator = generator
	return g
}

// MinLen returns the minimum generated byte length, including both affixes.
// It panics if the underlying minimum is negative or the total overflows int.
func (g AffixGenerator) MinLen() int {
	checkGenerator(g.generator)

	const maxInt = int(^uint(0) >> 1)
	minlen := g.generator.MinLen()
	if minlen < 0 || minlen > maxInt-len(g.prefix) {
		panic("stringx.AffixGenerator: invalid minimum length")
	}

	minlen += len(g.prefix)
	if minlen > maxInt-len(g.suffix) {
		panic("stringx.AffixGenerator: minimum length overflows int")
	}

	return minlen + len(g.suffix)
}

// Generate returns a string including the affixes. See [Generator] for length handling.
func (g AffixGenerator) Generate(length int) string { return generateString(g, length) }

// Append appends a generated string including the affixes to dst.
// See [Generator] for length handling.
func (g AffixGenerator) Append(dst []byte, length int) []byte {
	length = checkGeneratorLength(length, g.MinLen())
	length -= len(g.prefix) + len(g.suffix)
	dst = append(dst, g.prefix...)
	oldlen := len(dst)
	dst = g.generator.Append(dst, length)
	checkGeneratedLength(len(dst)-oldlen, length)
	return append(dst, g.suffix...)
}

var _ Generator = AffixGenerator{}
