// Copyright 2026 xgfone
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package stringx

import (
	"strconv"
	"time"

	"github.com/xgfone/go-toolkit/random"
	"github.com/xgfone/go-toolkit/timex"
)

var (
	dateTimeMilliRandGenerator = NewGenerator(18, appendDateTimeMilliRand)
	unixTimeMilliRandGenerator = NewGenerator(14, appendUnixTimeMilliRand)
	dateTimeRandGenerator      = NewGenerator(15, appendDateTimeRand)
	unixTimeRandGenerator      = NewGenerator(11, appendUnixTimeRand)
)

// DateTimeMilliRandGenerator returns a generator of YYYYMMDDHHMMSSmmm followed
// by random decimal digits, with a minimum length of 18 bytes. It uses [timex.Now].
func DateTimeMilliRandGenerator() Generator { return dateTimeMilliRandGenerator }

// UnixTimeMilliRandGenerator returns a generator of Unix milliseconds followed
// by random decimal digits, with a minimum length of 14 bytes. It uses [timex.Now].
func UnixTimeMilliRandGenerator() Generator { return unixTimeMilliRandGenerator }

// DateTimeRandGenerator returns a generator of YYYYMMDDHHMMSS followed by random
// decimal digits, with a minimum length of 15 bytes. It uses [timex.Now].
func DateTimeRandGenerator() Generator { return dateTimeRandGenerator }

// UnixTimeRandGenerator returns a generator of Unix seconds followed by random
// decimal digits, with a minimum length of 11 bytes. It uses [timex.Now].
func UnixTimeRandGenerator() Generator { return unixTimeRandGenerator }

// appendTimeRand generates a string with the given length and
// appends it to the given buffer.
//
// If the length of string generated by the generator function
// is less than the given length, it will be filled with random numbers.
//
// Note: length is the length of bytes generated by appendTimeRand,
// not the total length of buf.
func appendTimeRand(buf []byte, length int, g func([]byte, time.Time) []byte) []byte {
	oldlen := len(buf)
	buf = g(buf, timex.Now())

	for len(buf)-oldlen < length {
		var n int64

		switch length - (len(buf) - oldlen) {
		case 1:
			n = random.Int64N(1e1)
		case 2:
			n = random.Int64N(1e2)
		case 3:
			n = random.Int64N(1e3)
		case 4:
			n = random.Int64N(1e4)
		case 5:
			n = random.Int64N(1e5)
		case 6:
			n = random.Int64N(1e6)
		case 7:
			n = random.Int64N(1e7)
		case 8:
			n = random.Int64N(1e8)
		default:
			n = random.Int64N(1e9)
		}

		buf = strconv.AppendInt(buf, n, 10)
	}

	return buf
}

func appendDateTimeMilliRand(buf []byte, length int) []byte {
	return appendTimeRand(buf, length, func(b []byte, now time.Time) []byte {
		b = now.AppendFormat(b, "20060102150405")
		millis := now.Nanosecond() / int(time.Millisecond)
		b = append(b, byte('0'+millis/100), byte('0'+millis/10%10), byte('0'+millis%10))
		return b
	})
}

func appendUnixTimeMilliRand(buf []byte, length int) []byte {
	return appendTimeRand(buf, length, func(b []byte, now time.Time) []byte {
		return strconv.AppendInt(b, now.UnixMilli(), 10)
	})
}

func appendDateTimeRand(buf []byte, length int) []byte {
	return appendTimeRand(buf, length, func(b []byte, now time.Time) []byte {
		return now.AppendFormat(b, "20060102150405")
	})
}

func appendUnixTimeRand(buf []byte, length int) []byte {
	return appendTimeRand(buf, length, func(b []byte, now time.Time) []byte {
		return strconv.AppendInt(b, now.Unix(), 10)
	})
}
