// Copyright 2026 xgfone
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package stringx

import (
	"fmt"
	"strconv"
	"time"

	"github.com/xgfone/go-toolkit/random"
	"github.com/xgfone/go-toolkit/timex"
	"github.com/xgfone/go-toolkit/unsafex"
)

// DefaultBuilder is the default global builder used to generate a string.
var DefaultBuilder = NewBuilder(DateTimeMilliRandGenerator)

// Builder is used to build a string.
type Builder struct {
	prefix string
	suffix string

	generator Generator
}

// NewBuilder returns a new Builder with the given generator.
func NewBuilder(generator Generator) Builder {
	if generator == nil {
		panic("stringx.NewBuilder: generator must not be nil")
	}
	return Builder{generator: generator}
}

// WithPrefix sets the prefix of the string and returns a new Builder.
func (b Builder) WithPrefix(prefix string) Builder {
	b.prefix = prefix
	return b
}

// WithSuffix sets the suffix of the string and returns a new Builder.
func (b Builder) WithSuffix(suffix string) Builder {
	b.suffix = suffix
	return b
}

// WithGenerator sets the string generator and returns a new Builder.
func (b Builder) WithGenerator(generator Generator) Builder {
	if generator == nil {
		panic("stringx.Builder.Generate: generator must not be nil")
	}

	b.generator = generator
	return b
}

// Build builds a string of the given length.
//
// If length is equal to or less than 0, it will be set to the minimum length.
func (b Builder) Build(length int) (s string) {
	length = b.check(length)
	buf := make([]byte, 0, length)
	buf = b.generate(buf, length)
	return unsafex.String(buf)
}

// Generate implements the Generator interface.
func (b Builder) Generate(buf []byte, length int) []byte {
	length = b.check(length)
	return b.generate(buf, length)
}

// MinLen returns the minimum length of the generated string.
func (b Builder) MinLen() int {
	return len(b.prefix) + len(b.suffix) + b.generator.MinLen()
}

func (b Builder) check(length int) int {
	if length <= 0 {
		return b.MinLen()
	}

	if minlen := b.MinLen(); length < minlen {
		panic(fmt.Errorf("stringx.Builder: length must not be less than %d", minlen))
	}

	return length
}

func (b Builder) generate(buf []byte, length int) []byte {
	buf = append(buf, b.prefix...)
	buf = b.generator.Generate(buf, length)
	buf = append(buf, b.suffix...)
	return buf
}

var _ Generator = Builder{}

// Generator is used to generate a fixed-length string.
type Generator interface {
	// MinLen returns the minimal length of the generated string.
	MinLen() int

	// Generate generates a string and appends it to the given buffer.
	Generate(buf []byte, length int) (newbuf []byte)
}

type _Generator struct {
	minlen   int
	generate func([]byte, int) []byte
}

func (g _Generator) MinLen() int                         { return g.minlen }
func (g _Generator) Generate(buf []byte, len int) []byte { return g.generate(buf, len) }

// NewGenerator returns a new Generator with the given length and generator function.
func NewGenerator(minlen int, generate func(buf []byte, length int) []byte) Generator {
	return _Generator{minlen: minlen, generate: generate}
}

var (
	// Generate an 18-character string in the format "YYYYMMDDHHMMSSmmm1".
	DateTimeMilliRandGenerator = NewGenerator(18, generateDateTimeMilliRand)

	// Generate a 14-character string in the format "1767493069mmm1".
	UnixTimeMilliRandGenerator = NewGenerator(14, generateUnixTimeMilliRand)

	// Generate a 15-character string in the format "YYYYMMDDHHMMSS1".
	DateTimeRandGenerator = NewGenerator(15, generateDateTimeRand)

	// Generate a 11-character string in the format "17674930691".
	UnixTimeRandGenerator = NewGenerator(11, generateUnixTimeRand)
)

// Generate generates a string with the given length and
// appends it to the given buffer.
//
// If the length of string generated by the generator function
// is less than the given length, it will be filled with random numbers.
func Generate(buf []byte, length int, g func([]byte, time.Time) []byte) []byte {
	oldlen := len(buf)
	buf = g(buf, timex.Now())

	for len(buf)-oldlen < length {
		var n int64

		switch length - len(buf) {
		case 1:
			n = random.Int64N(1e1)
		case 2:
			n = random.Int64N(1e2)
		case 3:
			n = random.Int64N(1e3)
		case 4:
			n = random.Int64N(1e4)
		case 5:
			n = random.Int64N(1e5)
		case 6:
			n = random.Int64N(1e6)
		case 7:
			n = random.Int64N(1e7)
		case 8:
			n = random.Int64N(1e8)
		default:
			n = random.Int64N(1e9)
		}

		buf = strconv.AppendInt(buf, n, 10)
	}

	return buf
}

func generateDateTimeMilliRand(buf []byte, length int) []byte {
	return Generate(buf, length, func(b []byte, now time.Time) []byte {
		b = now.AppendFormat(b, "20060102150405")
		b = strconv.AppendInt(b, now.UnixMilli()%1000, 10)
		return b
	})
}

func generateUnixTimeMilliRand(buf []byte, length int) []byte {
	return Generate(buf, length, func(b []byte, now time.Time) []byte {
		return strconv.AppendInt(b, now.UnixMilli(), 10)
	})
}

func generateDateTimeRand(buf []byte, length int) []byte {
	return Generate(buf, length, func(b []byte, now time.Time) []byte {
		return now.AppendFormat(b, "20060102150405")
	})
}

func generateUnixTimeRand(buf []byte, length int) []byte {
	return Generate(buf, length, func(b []byte, now time.Time) []byte {
		return strconv.AppendInt(b, now.Unix(), 10)
	})
}
