name: Go
on: push
env:
  DEBUG: true
jobs:
  build:
    runs-on: ubuntu-latest
    name: Go ${{ matrix.go }}
    strategy:
      matrix:
        go:
          - "1.22"
          - "1.23"
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - run: |
          # just for file path from stacks.
          mkdir -p /home/runner/go/src/github.com/xgfone/go-toolkit
          cp -r ./* /home/runner/go/src/github.com/xgfone/go-toolkit
          cd /home/runner/go/src/github.com/xgfone/go-toolkit
          go test -cover -race ./...
